# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# run: python3 -m venv ./venv
#      source venv/bin/activate
#      python3 mainMenu.py
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QPixmap
import buildMode
import disasmbleMode
import quizMode


class Ui_MainMenu(object):

    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1000,800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainMenu.setSizePolicy(sizePolicy)
        #MainMenu.setMinimumSize(QtCore.QSize(1000, 800))

        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        
        self.background = QtWidgets.QLabel(MainMenu)
        self.background.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap('../images/mainmenu_background.png'))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background.lower()
        
        #self.background.setStyleSheet("background-image:url(../images/mainmenu_background.png); background-image")
        
        self.buildModeButton = QtWidgets.QPushButton(self.centralwidget)
        self.buildModeButton.setGeometry(QtCore.QRect(400, 420, 200, 31))
        self.buildModeButton.setObjectName("BuildModeButton")
        self.buildModeButton.clicked.connect(self.openBuildMode)
        self.buildModeButton.clicked.connect(MainMenu.close)

        self.disasmbleModeButton = QtWidgets.QPushButton(self.centralwidget)
        self.disasmbleModeButton.setGeometry(QtCore.QRect(400, 490, 200, 31))
        self.disasmbleModeButton.setObjectName("disasmbleModeButton")
        self.disasmbleModeButton.clicked.connect(self.openDisasmbleMode)
        self.disasmbleModeButton.clicked.connect(MainMenu.close)


        self.quizModeButton = QtWidgets.QPushButton(self.centralwidget)
        self.quizModeButton.setGeometry(QtCore.QRect(400, 560, 200, 31))
        self.quizModeButton.setObjectName("quizModeButton")
        self.quizModeButton.clicked.connect(self.openQuizMode)
        self.quizModeButton.clicked.connect(MainMenu.close)
        
        self.audioButton = QtWidgets.QPushButton(self.centralwidget)
        self.audioButton.setGeometry(QtCore.QRect(400, 630, 200, 31))
        self.audioButton.clicked.connect(lambda: self.playsound())
        self.audioButton.setObjectName("audioButton")

        self.audioButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.audioButton2.setGeometry(QtCore.QRect(400, 630, 200, 31))
        self.audioButton2.clicked.connect(lambda: self.stopSound())
        self.audioButton2.setObjectName("audioButton2")
        self.audioButton2.hide()

        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(400, 700, 200, 31))
        self.exit.setObjectName("Exit")
        self.exit.setText("Exit")
        self.exit.clicked.connect(MainMenu.close)

        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(90, 280, 820, 100))
        self.titleLabel.setStyleSheet("color: white")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont("Helvetica Black")
        font.setPointSize(37)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        
        MainMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)
        self.playsound()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buildModeButton.setText(_translate("MainWindow", "Build Mode"))
        self.disasmbleModeButton.setText(_translate("MainWindow", "Disassemble Mode"))
        self.quizModeButton.setText(_translate("MainWindow", "Quiz Mode"))
        self.audioButton.setText(_translate("MainWindow", "Audio"))
        self.audioButton2.setText((_translate("MainWindow","Audio")))
        self.titleLabel.setText(_translate("MainWindow", "PC Hardware Tutorial"))
        self.background.setText(_translate("MainWindow",""))
        
    def openQuizMode(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = quizMode.Ui_Quiz()
        self.ui.setupQuiz(self.window)
        self.stopSound()
        self.window.show()

    def openBuildMode(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = buildMode.Ui_MotherBoard()
        self.ui.setupHardware(self.window)
        self.ui.setupMotherboard(self.window)
        self.stopSound()
        self.window.show()
    
    def openDisasmbleMode(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = disasmbleMode.Ui_MotherBoard()
        self.ui.setupHardware(self.window)
        self.ui.setupMotherboard(self.window)
        self.stopSound()
        self.window.show()

    def playsound(self):
        self.music_player = QMediaPlayer()
        self.full_file_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'sounds/backgroundMusic.mp3')
        self.url = QUrl.fromLocalFile(self.full_file_path)
        self.music_player.setMedia(QMediaContent(self.url))
        self.music_player.play()
        self.audioButton2.show()
        self.audioButton.hide()

    def stopSound(self):
        self.music_player.stop()
        self.audioButton.show()
        self.audioButton2.hide()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QMainWindow()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec_())
