# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiz_finish.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
import mainMenu


class Ui_QuizComplete(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_image = QtWidgets.QLabel(self.centralwidget)
        self.background_image.setGeometry(QtCore.QRect(0, 0, 1031, 661))
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap("../images/quiz_background.PNG"))
        self.background_image.setScaledContents(True)
        self.background_image.setObjectName("background_image")
        self.quiz_complete_label = QtWidgets.QLabel(self.centralwidget)
        self.quiz_complete_label.setGeometry(QtCore.QRect(370, 40, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.quiz_complete_label.setFont(font)
        self.quiz_complete_label.setStyleSheet("color: rgb(255, 215, 0);")
        self.quiz_complete_label.setAlignment(QtCore.Qt.AlignCenter)
        self.quiz_complete_label.setObjectName("title")
        self.trophy_image = QtWidgets.QLabel(self.centralwidget)
        self.trophy_image.setGeometry(QtCore.QRect(670, 140, 321, 381))
        self.trophy_image.setText("")
        self.trophy_image.setPixmap(QtGui.QPixmap("../images/trophy.PNG"))
        self.trophy_image.setScaledContents(True)
        self.trophy_image.setObjectName("trophy_image")
        self.confetti = QtWidgets.QLabel(self.centralwidget)
        self.confetti.setGeometry(QtCore.QRect(680, 90, 290, 481))
        self.confetti.setText("")
        self.confetti.setScaledContents(True)
        self.confetti.setObjectName("confetti")
        self.confetti_movie = QMovie("../images/confetti.gif")
        self.confetti.setMovie(self.confetti_movie)
        self.confetti_movie.start()

        self.congrats_label = QtWidgets.QLabel(self.centralwidget)
        self.congrats_label.setGeometry(QtCore.QRect(60, 170, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.congrats_label.setFont(font)
        self.congrats_label.setStyleSheet("color:rgb(0, 255, 255);")
        self.congrats_label.setAlignment(QtCore.Qt.AlignCenter)
        self.congrats_label.setWordWrap(True)
        self.congrats_label.setObjectName("congrats_label")
        self.main_menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.main_menu_button.setGeometry(QtCore.QRect(70, 540, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        font.setUnderline(False)
        self.main_menu_button.setFont(font)
        self.main_menu_button.setStyleSheet("color:rgb(0, 255, 255);"
                                        "background-color: rgb(33, 33, 33);")
        self.main_menu_button.setObjectName("main_menu_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(350, 540, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("color:rgb(0, 255, 255);"
                                        "background-color: rgb(33, 33, 33);")
        self.exit_button.setObjectName("exit_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 100, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 215, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.built_mobo_image = QtWidgets.QLabel(self.centralwidget)
        self.built_mobo_image.setGeometry(QtCore.QRect(140, 270, 231, 211))
        self.built_mobo_image.setText("")
        self.built_mobo_image.setPixmap(QtGui.QPixmap("../images/built_motherboard.png"))
        self.built_mobo_image.setScaledContents(True)
        self.built_mobo_image.setObjectName("built_mobo_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Main menu button
        self.main_menu_button.clicked.connect(lambda: self.openMain())
        self.main_menu_button.clicked.connect(MainWindow.close)

        # Exit button
        self.exit_button.clicked.connect(MainWindow.close)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.quiz_complete_label.setText(_translate("MainWindow", "Hardware Quiz Complete!"))
        self.congrats_label.setText(_translate("MainWindow", "Congratulations! You now have the knowledge to build your own PC!"))
        self.main_menu_button.setText(_translate("MainWindow", "Main Menu"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "Answered Correct: 9/9"))

    def openMain(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = mainMenu.Ui_MainMenu()
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    quiz_complete = Ui_QuizComplete()
    quiz_complete.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())