# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hardware.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupHardware(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 986)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cpu_label = QtWidgets.QLabel(self.centralwidget)
        self.cpu_label.setGeometry(QtCore.QRect(1040, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.cpu_label.setFont(font)
        self.cpu_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_label.setObjectName("cpu_label")
        self.cpu_img = QtWidgets.QLabel(self.centralwidget)
        self.cpu_img.setGeometry(QtCore.QRect(1070, 110, 91, 81))
        self.cpu_img.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cpu_img.setText("")
        self.cpu_img.setPixmap(QtGui.QPixmap("../images/i7_cpu.jpg"))
        self.cpu_img.setScaledContents(True)
        self.cpu_img.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_img.setObjectName("cpu_img")
        self.cpu_cooler_img = QtWidgets.QLabel(self.centralwidget)
        self.cpu_cooler_img.setGeometry(QtCore.QRect(1240, 100, 111, 111))
        self.cpu_cooler_img.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cpu_cooler_img.setText("")
        self.cpu_cooler_img.setPixmap(QtGui.QPixmap("../images/cpu_cooler.png"))
        self.cpu_cooler_img.setScaledContents(True)
        self.cpu_cooler_img.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_cooler_img.setObjectName("cpu_cooler_img")
        self.cpu_cooler_label = QtWidgets.QLabel(self.centralwidget)
        self.cpu_cooler_label.setGeometry(QtCore.QRect(1220, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.cpu_cooler_label.setFont(font)
        self.cpu_cooler_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_cooler_label.setObjectName("cpu_cooler_label")
        self.hardware_list_label = QtWidgets.QLabel(self.centralwidget)
        self.hardware_list_label.setGeometry(QtCore.QRect(1100, 10, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.hardware_list_label.setFont(font)
        self.hardware_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.hardware_list_label.setObjectName("hardware_list_label")
        self.cpu_img_2 = QtWidgets.QLabel(self.centralwidget)
        self.cpu_img_2.setGeometry(QtCore.QRect(1090, 250, 221, 121))
        self.cpu_img_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cpu_img_2.setText("")
        self.cpu_img_2.setPixmap(QtGui.QPixmap("../images/gpu.png"))
        self.cpu_img_2.setScaledContents(True)
        self.cpu_img_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_img_2.setObjectName("cpu_img_2")
        self.cpu_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.cpu_label_2.setGeometry(QtCore.QRect(1130, 210, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.cpu_label_2.setFont(font)
        self.cpu_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_label_2.setObjectName("cpu_label_2")
        self.cpu_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.cpu_label_3.setGeometry(QtCore.QRect(1140, 370, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.cpu_label_3.setFont(font)
        self.cpu_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_label_3.setObjectName("cpu_label_3")
        self.cpu_cooler_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.cpu_cooler_label_3.setGeometry(QtCore.QRect(1140, 530, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.cpu_cooler_label_3.setFont(font)
        self.cpu_cooler_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_cooler_label_3.setObjectName("cpu_cooler_label_3")
        self.cpu_cooler_img_3 = QtWidgets.QLabel(self.centralwidget)
        self.cpu_cooler_img_3.setGeometry(QtCore.QRect(1090, 560, 251, 61))
        self.cpu_cooler_img_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cpu_cooler_img_3.setText("")
        self.cpu_cooler_img_3.setPixmap(QtGui.QPixmap("../images/m.2_ssd.jpg"))
        self.cpu_cooler_img_3.setScaledContents(True)
        self.cpu_cooler_img_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_cooler_img_3.setObjectName("cpu_cooler_img_3")
        self.cpu_img_3 = QtWidgets.QLabel(self.centralwidget)
        self.cpu_img_3.setGeometry(QtCore.QRect(1100, 410, 221, 51))
        self.cpu_img_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cpu_img_3.setText("")
        self.cpu_img_3.setPixmap(QtGui.QPixmap("../images/ram stick.jpg"))
        self.cpu_img_3.setScaledContents(True)
        self.cpu_img_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_img_3.setObjectName("cpu_img_3")
        self.cpu_img_5 = QtWidgets.QLabel(self.centralwidget)
        self.cpu_img_5.setGeometry(QtCore.QRect(1100, 470, 221, 51))
        self.cpu_img_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cpu_img_5.setText("")
        self.cpu_img_5.setPixmap(QtGui.QPixmap("../images/ram stick.jpg"))
        self.cpu_img_5.setScaledContents(True)
        self.cpu_img_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cpu_img_5.setObjectName("cpu_img_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateHardware(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setupMotherboard(self, MainWindow):

            #Format is as follows for all components
        #Add to the GUI
        #Style sheet for hover and color of label
        #Set Coordinates x1 and y1 for placement x2 and y2 for size
        #Set mouse tracking on for dragging later
        #Clear text so we can have just the highlight w/o text
        #Name the label


        self.motherBoard = QtWidgets.QLabel(MainWindow)
        self.motherBoard.setGeometry(QtCore.QRect(0, 0, 801, 971))
        self.motherBoard.setMouseTracking(True)
        self.motherBoard.setPixmap(QtGui.QPixmap("../images/IntelMotherBoard.jpg"))
        self.motherBoard.setObjectName("MotherBoard")

        #Opacity effect doesn't work with multiple labels 
        #Also tried setting opacity 1 to 0 but it doesnt work
        #Forced to initialize new opacities w/ same values                                      

        self.opacityEffect0 = QGraphicsOpacityEffect()
        self.opacityEffect0.setOpacity(0.3)

        self.opacityEffect1 = QGraphicsOpacityEffect()
        self.opacityEffect1.setOpacity(0.3)

        self.opacityEffect2 = QGraphicsOpacityEffect()
        self.opacityEffect2.setOpacity(0.3)

        self.opacityEffect3 = QGraphicsOpacityEffect()
        self.opacityEffect3.setOpacity(0.3)

        self.opacityEffect4 = QGraphicsOpacityEffect()
        self.opacityEffect4.setOpacity(0.3)

        self.opacityEffect5 = QGraphicsOpacityEffect()
        self.opacityEffect5.setOpacity(0.3)

        self.opacityEffect6 = QGraphicsOpacityEffect()
        self.opacityEffect6.setOpacity(0.3)

        self.opacityEffect7 = QGraphicsOpacityEffect()
        self.opacityEffect7.setOpacity(0.3)

        #CPU ON LABEL
        self.cpu = QtWidgets.QLabel(self.centralwidget)
        self.cpu.setStyleSheet("QLabel::hover"
                               "{ background-color : yellow; }")
        self.cpu.setGeometry(QtCore.QRect(730, 170, 131, 211))
        self.cpu.setMouseTracking(True)
        self.cpu.clear()
        self.cpu.setObjectName("CPU")
        self.cpu.setGraphicsEffect(self.opacityEffect0)


        self.cpuCable = QtWidgets.QLabel(self.centralwidget)
        self.cpuCable.setStyleSheet("QLabel::hover"
                                   "{ background-color : yellow; }")
        self.cpuCable.setGeometry(QtCore.QRect(570, 19, 50, 25))
        self.cpuCable.setMouseTracking(True)
        self.cpuCable.clear()
        self.cpuCable.setObjectName("CPU-Cable")
        self.cpuCable.setGraphicsEffect(self.opacityEffect1)


        #GPU ON LABEL
        self.gpu = QtWidgets.QLabel(self.centralwidget)
        self.gpu.setStyleSheet("QLabel::hover"
                               "{ background-color : yellow; }")
        self.gpu.setGeometry(QtCore.QRect(570, 565, 321, 31))
        self.gpu.setMouseTracking(True)
        self.gpu.clear()
        self.gpu.setObjectName("GPU")
        self.gpu.setGraphicsEffect(self.opacityEffect2)
        
        #RAM STICKS ON LABELS
        self.ram1 = QtWidgets.QLabel(self.centralwidget)
        self.ram1.setStyleSheet("QLabel::hover"
                               "{ background-color : yellow }")
        self.ram1.setGeometry(QtCore.QRect(960, 50, 20, 440))
        self.ram1.setMouseTracking(True)
        self.ram1.clear()
        self.ram1.setObjectName("RamStick1")
        self.ram1.setGraphicsEffect(self.opacityEffect3)
      
        self.ram2 = QtWidgets.QLabel(self.centralwidget)
        self.ram2.setStyleSheet("QLabel::hover"
                               "{ background-color : yellow }")
        self.ram2.setGeometry(QtCore.QRect(989, 50, 20, 440))
        self.ram2.setMouseTracking(True)
        self.ram2.clear()
        self.ram2.setObjectName("RamStick2")
        self.ram2.setGraphicsEffect(self.opacityEffect4)
     
        self.ram3 = QtWidgets.QLabel(self.centralwidget)
        self.ram3.setStyleSheet("QLabel::hover"
                               "{ background-color : yellow }")
        self.ram3.setGeometry(QtCore.QRect(1018, 50, 20, 440))
        self.ram3.setMouseTracking(True)
        self.ram3.clear()
        self.ram3.setObjectName("RamStick3")
        self.ram3.setGraphicsEffect(self.opacityEffect5)

        self.ram4 = QtWidgets.QLabel(self.centralwidget)
        self.ram4.setStyleSheet("QLabel::hover"
                               "{ background-color : yellow }")
        self.ram4.setGeometry(QtCore.QRect(1047, 50, 20, 440))
        self.ram4.setMouseTracking(True)
        self.ram4.clear()
        self.ram4.setObjectName("RamStick4")
        self.ram4.setGraphicsEffect(self.opacityEffect6)


        #label 8 is m.2
        self.m2 = QtWidgets.QLabel(self.centralwidget)
        self.m2.setStyleSheet("QLabel::hover"
                             "{ background-color : yellow }")
        self.m2.setGeometry(QtCore.QRect(860, 830, 251, 71))
        self.m2.clear()
        self.m2.setObjectName("M.2 SSD")
        self.m2.setGraphicsEffect(self.opacityEffect7)


        self.retranslateMotherboard(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(self.centralwidget)
    
    def retranslateMotherboard(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.centralwidget.setWindowTitle(_translate("MotherBoard", "MotherBoard"))

    def retranslateHardware(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cpu_label.setText(_translate("MainWindow", "CPU"))
        self.cpu_cooler_label.setText(_translate("MainWindow", "CPU Cooler"))
        self.hardware_list_label.setText(_translate("MainWindow", "Hardware Components"))
        self.cpu_label_2.setText(_translate("MainWindow", "GPU"))
        self.cpu_label_3.setText(_translate("MainWindow", "RAM Sticks"))
        self.cpu_cooler_label_3.setText(_translate("MainWindow", "M.2 SSD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupHardware(MainWindow)
    ui.setupMotherboard(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
