# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtdesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# run: python3 -m venv ./venv
#      source venv/bin/activate
#      python3 mainMenu.py

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QPixmap
import buildMode 

class Ui_MainMenu(object):
    def setupUi(self, MainWindow):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1000,800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainMenu.setSizePolicy(sizePolicy)
        #MainMenu.setMinimumSize(QtCore.QSize(1000, 800))

        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        
        self.background = QtWidgets.QLabel(MainMenu)
        self.background.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap('../images/mainmenu_background.png'))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background.lower()
        
        #self.background.setStyleSheet("background-image:url(../images/mainmenu_background.png); background-image")
        

        
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(400, 490, 200, 31))
        self.startButton.setObjectName("BuildModeButton")
        self.startButton.clicked.connect(self.openBuildMode)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 570, 200, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(90, 280, 
        820, 100))
        self.titleLabel.setStyleSheet("color: white")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont("Helvetica Black")
        font.setPointSize(37)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        MainMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Build Mode"))
        self.pushButton_2.setText(_translate("MainWindow", "Audio"))
        self.titleLabel.setText(_translate("MainWindow", "Learn Computer Hardware"))
        self.background.setText(_translate("MainWindow",""))
        
    def openBuildMode(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = buildMode.Ui_MotherBoard()
        self.ui.setupHardware(self.window)
        self.ui.setupMotherboard(self.window)
        MainMenu.hide()
        self.window.show()

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QMainWindow()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec_())
