# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PartaAnalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QMimeData, Qt
from PyQt5.QtGui import QDrag, QPixmap, QPainter, QCursor, QImage
from PyQt5.QtCore import *

partNames = ["CPU", "GPU", "CPU-COOLER", "RAM", "SSD", "MotherBoard", "Cmos"]
io_partNames = ["ANTENNA", "HDMI", "USB3.2_PS2", "USB3.2_TypeA_TypeC", "LAN_USB2.0", "AUDIO-JACKS"]

#Index is CPU as 0, GPU, RAM, CPU-COOLER, SSD
descriptions = ["The CPU or Central Processing Unit is the brain of a computer,"
                " containing all the circuitry needed to process input,"
                " store data, and output results. The CPU is constantly following"
                " instructions of computer programs that tell it which data to process"
                " and how to process it.",

                "The GPU or Graphics processing unit, is a specialized"
                " processor originally designed to accelerate graphics rendering"
                " i.e. it displays the picture onto your screen",

                "The CPU cooler is a device designed to draw heat away from the system's"
                " CPU and other components in the enclosure.",

                "Ram or random-access memory is where the computer stores data that is needed for short term memory."
                " The ram holds all the data you are currently using.",

                "The SSD or Solid-State drive is a new generation of storage device"
                " used in computers. An SSD is much faster than a tradition mechanical"
                " hard disk as it uses flash-based memory instead of a physical disk",

                "MotherBoard",

                "Cmos"]

descriptions2 = ["The CPU or Central Processing Unit is the brain of a computer,"
                " containing all the circuitry needed to process input,"
                " store data, and output results. The CPU is constantly following"
                " instructions of computer programs that tell it which data to process"
                " and how to process it.",

                "The GPU or Graphics processing unit, is a specialized"
                " processor originally designed to accelerate graphics rendering"
                " i.e. it displays the picture onto your screen",

                "The CPU cooler is a device designed to draw heat away from the system's"
                " CPU and other components in the enclosure.",

                "Ram or random-access memory is where the computer stores data that is needed for short term memory."
                " The ram holds all the data you are currently using.",

                "The SSD or Solid-State drive is a new generation of storage device"
                " used in computers. An SSD is much faster than a tradition mechanical"
                " hard disk as it uses flash-based memory instead of a physical disk"]

io_descriptions1 = ["Antenna Ports", "Hdmi", "PS/2 Ports and USB 3.2 ports",
                    "USB 3.2 Type-A port and USB 3.2 Type-C port", "LAN/Ethernet port and USB 2.0 port",
                    "Audio jacks port"]
io_descriptions2 = ["Gets signal", "Transfers data"]

class Ui_PartAnalyzer(object):
    def setupUi(self, PartAnalyzer, name, description, image1, image2, width, height, width2, height2):
        PartAnalyzer.setObjectName("PartAnalyzer")
        PartAnalyzer.resize(800, 600)
        PartAnalyzer.setAutoFillBackground(False)
        self.background = QtWidgets.QLabel(PartAnalyzer)
        self.background.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap('../images/partback.png'))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background.lower()

        self.centralwidget = QtWidgets.QWidget(PartAnalyzer)
        self.centralwidget.setObjectName("centralwidget")
        self.PartImage = QtWidgets.QLabel(self.centralwidget)
        self.PartImage.setGeometry(QtCore.QRect(80, 100, width, height))
        self.PartImage.clear()
        self.PartImage.setObjectName("PartImage")
        self.PartImage.setPixmap(QtGui.QPixmap(image1))
        self.PartImage.setScaledContents(True)
        self.partImage2 = QtWidgets.QLabel(self.centralwidget)
        self.partImage2.setGeometry(QtCore.QRect(80, 300, width2, height2))
        self.partImage2.clear()
        self.partImage2.setObjectName("PartImage2")
        self.partImage2.setPixmap(QtGui.QPixmap(image2))
        self.partImage2.resize(width2, height2)
        self.partImage2.setScaledContents(True)
        self.partImage2.raise_()

        self.PartName = QtWidgets.QLabel(self.centralwidget)
        self.PartName.setGeometry(QtCore.QRect(300, 20, 251, 51))
        self.PartName.setObjectName("PartName")
        self.PartName.setText(name)
        self.PartName.setStyleSheet(("font-size: 16pt; color: white;"))

        self.Parttitle = QtWidgets.QLabel(self.centralwidget)
        self.Parttitle.setGeometry(QtCore.QRect(480, 120, 251, 51))
        self.Parttitle.setObjectName("PartName")
        self.Parttitle.setText("What is it?")
        self.Parttitle.setStyleSheet(("font-size: 16pt; color: white;"))

        self.Parttitle = QtWidgets.QLabel(self.centralwidget)
        self.Parttitle.setGeometry(QtCore.QRect(480, 360, 251, 51))
        self.Parttitle.setObjectName("PartName")
        self.Parttitle.setText("What Does it do?")
        self.Parttitle.setStyleSheet(("font-size: 16pt; color: white;"))


        self.PartDescription = QtWidgets.QLabel(self.centralwidget)
        self.PartDescription.setGeometry(QtCore.QRect(480, 160, 250, 200))
        self.PartDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.PartDescription.setObjectName("PartDescription")
        self.PartDescription.setText(description)
        self.PartDescription.setWordWrap(True)
        self.PartDescription.setStyleSheet(("font-size: 12pt; color: white;"))

        self.PartDescription2 = QtWidgets.QLabel(self.centralwidget)
        self.PartDescription2.setGeometry(QtCore.QRect(480, 400, 250, 200))
        self.PartDescription2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.PartDescription2.setObjectName("PartDescription")
        self.PartDescription2.setText(description)
        self.PartDescription2.setWordWrap(True)
        self.PartDescription2.setStyleSheet(("font-size: 12pt; color: white;"))


        PartAnalyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PartAnalyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        PartAnalyzer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PartAnalyzer)
        self.statusbar.setObjectName("statusbar")
        PartAnalyzer.setStatusBar(self.statusbar)
        QtCore.QMetaObject.connectSlotsByName(PartAnalyzer)
#Test
def window2():
    app1 = QtWidgets.QApplication(sys.argv)
    PartAnalyzer1 = QtWidgets.QMainWindow()
    ui1 = Ui_PartAnalyzer()
    #width height of first image, width height of second image
    ui1.setupUi(PartAnalyzer1, "Graphics Processing Unit", descriptions[1], "../images/gpu.png", "../images/gpu2.png", 300, 200, 400, 200)
    PartAnalyzer1.show()
    sys.exit(app1.exec_())
    #print(Ui_PartAnalyzer.partDescriptions(0))
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PartAnalyzer = QtWidgets.QMainWindow()
    ui = Ui_PartAnalyzer()
    ui.setupUi(PartAnalyzer, "Central Processing Unit", descriptions[0], "../images/i7_cpu.jpg", "../images/ryzen9.JPG", 200, 200, 200, 200)
    PartAnalyzer.show()
    window2()

    sys.exit(app.exec_())
